@echo off
echo Starting Backend Server (WhatsApp Messaging)...
start cmd /k "python server.py"

echo Starting Frontend Server...
start cmd /k "python -m http.server 8000"

echo Waiting for servers to start...
timeout /t 3 /nobreak >nul

echo Opening browser...
start http://localhost:8000
